// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230331183053_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Breed = "Chihuahua",
                            Gender = "Male",
                            Name = "Conan",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Breed = "ShortHair",
                            Gender = "Female",
                            Name = "Curtesia",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Breed = "GoldenRetriever",
                            Gender = "Male",
                            Name = "Chauncey",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Breed = "ShortHair",
                            Gender = "Male",
                            Name = "Curtis",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Breed = "Corgi",
                            Gender = "Female",
                            Name = "Ginger",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Breed = "Corgi",
                            Gender = "Male",
                            Name = "Winston",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Breed = "Siamese",
                            Gender = "Male",
                            Name = "Sugar",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Breed = "Airedale",
                            Gender = "Female",
                            Name = "Valerie",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 9,
                            Breed = "LongHair",
                            Gender = "Male",
                            Name = "Mingus",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 10,
                            Breed = "Dachshund",
                            Gender = "Male",
                            Name = "Dexter",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 11,
                            Breed = "ShortHair",
                            Gender = "Male",
                            Name = "Mingus",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 12,
                            Breed = "Boxer",
                            Gender = "Female",
                            Name = "Jasmine",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 13,
                            Breed = "Siamese",
                            Gender = "Male",
                            Name = "Linus",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 14,
                            Breed = "Beagle",
                            Gender = "Female",
                            Name = "Petunia",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 15,
                            Breed = "Bulldog",
                            Gender = "Male",
                            Name = "Tiny",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 16,
                            Breed = "ShortHair",
                            Gender = "Female",
                            Name = "Minnie",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 17,
                            Breed = "ShortHair",
                            Gender = "Male",
                            Name = "Marvin",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 18,
                            Breed = "Pomeranian",
                            Gender = "Male",
                            Name = "Fizzgig",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 19,
                            Breed = "LongHair",
                            Gender = "Male",
                            Name = "Wolfie",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 20,
                            Breed = "Husky",
                            Gender = "Female",
                            Name = "Pandora",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 21,
                            Breed = "ShihTzu",
                            Gender = "Male",
                            Name = "Batman",
                            Species = "dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
